language: php

php:
  - 7.0
  - 7.1

env:
  - TRAVIS_NODE_VERSION="7"

addons:
  mariadb: '10.0'

sudo: required

before_script:
  - sudo rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - cp .env.travis .env
  - mysql -u root -e 'create database homestead;'
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - composer dump-autoload
  - php artisan db:seed
  - php artisan passport:install
  - yarn
  - cp resources/assets/js/lib/pusher-conf.js.example resources/assets/js/lib/pusher-conf.js
  - yarn run production

cache:
  yarn: true

script:
  - composer test

after_success:
    - bash <(curl -s https://codecov.io/bash)
