language: php

php:
  - 7.1

sudo: required

before_script:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - composer du
  - php artisan key:generate
  - yarn
  - yarn run prod

cache:
  yarn: true

script:
  - vendor/bin/phpunit
