128.199.75.218:
  repository: https://github.com/nipeharefa/IShoupBuddy
  deploy_path: /var/www/Skripsi2
  branch: master
  domain: shoupbud.xyz
  port: 2222
  user: root
  identityFile: ~
  forwardAgent: true
  multiplexing: true
